#!/usr/bin/env python3
"""Generate INDEX.md from skill frontmatter."""

from __future__ import annotations

import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent
INDEX = ROOT / "INDEX.md"
REQUIRED = ("name", "tier", "description")


def skill_files() -> list[Path]:
    paths: list[Path] = []
    for tier in ("generic", "dev"):
        directory = ROOT / tier
        if directory.is_dir():
            paths.extend(directory.glob("*/SKILL.md"))
    projects = ROOT / "projects"
    if projects.is_dir():
        paths.extend(projects.glob("*/SKILL.md"))
        paths.extend(projects.glob("*/*/SKILL.md"))
    return sorted(set(paths), key=lambda path: path.relative_to(ROOT).as_posix())


def frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"\A---\s*\n(.*?)\n---\s*(?:\n|\Z)", text, re.DOTALL)
    if not match:
        raise ValueError("missing YAML frontmatter")
    values: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, separator, value = line.partition(":")
        if separator:
            values[key.strip()] = value.strip().strip("'\"")
    missing = [key for key in REQUIRED if not values.get(key)]
    if missing:
        raise ValueError(f"missing frontmatter field(s): {', '.join(missing)}")
    return values


def cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def main() -> int:
    rows: list[tuple[str, str, str]] = []
    failed = False
    for path in skill_files():
        try:
            metadata = frontmatter(path)
        except ValueError as error:
            print(f"ERROR: {path.relative_to(ROOT)}: {error}", file=sys.stderr)
            failed = True
            continue
        changelog = path.with_name("CHANGELOG.md")
        if not changelog.exists():
            print(f"WARN: {path.relative_to(ROOT)} has no CHANGELOG.md", file=sys.stderr)
        elif path.stat().st_mtime > changelog.stat().st_mtime:
            print(
                f"WARN: {path.relative_to(ROOT)} is newer than {changelog.relative_to(ROOT)}",
                file=sys.stderr,
            )
        rows.append(tuple(cell(metadata[key]) for key in REQUIRED))
    if failed:
        return 1
    lines = [
        "# Skills Index",
        "",
        "<!-- Generated by gen-index.py. Do not edit by hand. -->",
        "",
        "| skill | tier | trigger |",
        "| --- | --- | --- |",
    ]
    lines.extend(f"| {name} | {tier} | {description} |" for name, tier, description in rows)
    INDEX.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
